---
name: Jess
surname: Esplin
position: "Ph.D. Student"
address: "Department of Political Science, University of Wisconsin-Madison"
phone: 801 663 9496
www: jessesplin.webpage.com
email: "jesplin@wisc.edu"
twitter: jessesplin
github: jesplin
linkedin: jessesplin
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::hyndman
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Some stuff about me

 * I poisoned myself doing research.
 * I was the first woman to win a Nobel prize
 * I was the first person and only woman to win a Nobel prize in two different sciences.

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Ph.D. in Political Science expected Spring 2025", "2020-Present", "University of Wisconsin-Madison", "Madison, Wisconsin",
  "Honors Bachelor of Science in Economics", "2016", "University of Utah", "Salt Lake City, Utah",
  "Bachelor of Science in Psychology", "2016", "University of Utah", "Salt Lake City, Utah"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Nobel Prizes

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

# Publications

```{r}
library(dplyr)
scholar::get_publications("EmD_lTEAAAAJ&EmD_lTEAAAAJ&") %>% 
  filter(cites > 30) %>% 
  distinct(title, .keep_all = TRUE) %>%
  transmute(bibtype = "Article", author = as.character(author),
            title = as.character(title),
            journaltitle = as.character(journal), year, key = row_number()) %>% 
  RefManageR::as.BibEntry() %>% 
  RefManageR::WriteBib("CV.bib")

bibliography_entries("CV.bib")
```

